app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('competitions');
});

Route::group(['middleware' => 'web'], function(){
	Route::match(['get', 'post'], 'update', 'UpdateController@index');

	Route::auth();

	// Route::get('/home', 'HomeController@index');

	Route::singularResourceParameters();

	Route::resource('clubs', 'ClubsController');
	Route::resource('competitions', 'CompetitionsController');
	Route::resource('competitions.games', 'GamesController');
	Route::resource('competitions.games.scorecards', 'ScorecardsController');
	Route::resource('players', 'PlayersController');
	Route::resource('ranks', 'RanksController');
	Route::resource('users', 'UsersController');

	Route::post('competitions/{competition}/find', 'CompetitionsController@find');
	Route::get('competitions/{competition}/inspect/{player}', 'CompetitionsController@inspect')->name('competitions.inspect');
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use EntrustUserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function path()
    {
        return route('users.show', ['user' => $this]);
    }

    public function editPath()
    {
        return route('users.edit', ['user' => $this]);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\User;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:owner|admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">@lang('users.create')</div>
                <div class="panel-body">
                    <form role="form" method="POST" action="{{ route('users.store') }}">
                        {!! csrf_field() !!}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label class="control-label">@lang('users.name')</label>

                            <input type="text" class="form-control" name="name" value="{{ old('name') }}" placeholder="@lang('users.name')">

                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label class="control-label">@lang('users.email')</label>

                            <input type="email" class="form-control" name="email" value="{{ old('email') }}" placeholder="@lang('users.email')">

                            @if ($errors->has('email'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('email') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">
                                @lang('actions.store')
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">@lang('actions.edit') {{ $user->name }}</div>
                <div class="panel-body">
                    <form role="form" method="POST" action="{{ route('users.store') }}">
                        {!! csrf_field() !!}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label class="control-label">@lang('users.name')</label>

                            <input type="text" class="form-control" name="name" value="{{ ($name = old('name')) ? $name : $user->name }}" placeholder="@lang('users.name')">

                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label class="control-label">@lang('users.email')</label>

                            <input type="email" class="form-control" name="email" value="{{ ($email = old('email')) ? $email : $user->email }}" placeholder="@lang('users.email')">

                            @if ($errors->has('email'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('email') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">
                                @lang('actions.store')
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    @lang('users.index')
                    <a href="{{ route('users.create') }}" class="pull-right">@lang('actions.create')</a>
                </div>
                <div class="panel-body">
                    <ul class="list-group">
                        @foreach ($users as $user)
                            <li class="list-group-item">
                                <a href="{{ $user->path() }}">{{ $user->name }}</a>
                                <a href="{{ $user->editPath() }}" class="pull-right">@lang('actions.edit')</a>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ $user->name }}
                    <a href="{{ $user->editPath() }}" class="pull-right">@lang('actions.edit')</a>
                </div>
                <div class="panel-body">
                    <div class="user-email">
                        <label>@lang('users.email'): </label>
                        <div>{{ $user->email }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection