app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('competitions');
});

Route::group(['middleware' => 'web'], function(){
	Route::match(['get', 'post'], 'update', 'UpdateController@index');

	Route::auth();

	// Route::get('/home', 'HomeController@index');

	Route::singularResourceParameters();

	Route::resource('clubs', 'ClubsController');
	Route::resource('competitions', 'CompetitionsController');
	Route::resource('competitions.games', 'GamesController');
	Route::resource('competitions.games.scorecards', 'ScorecardsController');
	Route::resource('players', 'PlayersController');
	Route::resource('ranks', 'RanksController');
	Route::resource('users', 'UsersController');

	Route::post('competitions/{competition}/find', 'CompetitionsController@find');
	Route::get('competitions/{competition}/inspect/{player}', 'CompetitionsController@inspect')->name('competitions.inspect');
});

app/Competition.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Competition extends Model
{
    protected $fillable = [
        'name',
        'shots_per_end',
        'distance',
        'points_type',
    ];

    public function games()
    {
    	return $this->hasMany(Game::class);
    }

    public function scorecards()
    {
        return $this->hasManyThrough(Scorecard::class, Game::class);
    }

    public function addGame(Game $game)
    {
    	return $this->games()->save($game);
    }

    public function path()
    {
    	return '/competitions/'.$this->id;
    }
}

app/Http/Controllers/CompetitionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Player;
use App\Scorecard;
use App\Competition;
use Khill\Lavacharts\Lavacharts;

class CompetitionsController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:owner|admin', ['except' => [
            'index',
            'show',
            'inspect',
        ]]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $competitions = Competition::orderBy('created_at', 'desc')->get();

        return view('competitions.index', compact('competitions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('competitions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:competitions',
            'distance' => 'required',
            'points_type' => 'required',
        ]);

        $competition = Competition::create($request->all());

        return redirect($competition->path());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Competition $competition)
    {
        $players = [];

        foreach ($competition->games as $game)
        {
            foreach ($game->scorecards as $scorecard)
            {
                if (!array_key_exists($scorecard->player->id, $players))
                    $players[$scorecard->player->id] = $scorecard->player;
            }
        }

        return view('competitions.show', compact('competition', 'players'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Competition $competition)
    {
        return view('competitions.edit', compact('competition'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Competition $competition)
    {
        $competition->update($request->all());

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function find(Request $request, Competition $competition)
    {
        $player = Player::find($request->player_id);

        return redirect('/competitions-inspect/'.$competition->id.'/'.$player->id);
    }

    public function inspect(Competition $competition, Player $player)
    {
        $points = 0;
        $pointsCount = 0;

        $specificPoints = [0 => 0, 1 => 0, 2 => 0, 3 => 0, 4 => 0, 5 => 0, 6 => 0, 7 => 0, 8 => 0, 9 => 0, 10 => 0, 'X' => 0];

        foreach ($competition->games as $game)
        {
            foreach ($game->scorecards as $scorecard)
            {
                $roundsCount = 0;

                foreach ($scorecard->rounds() as $round)
                {
                    $shotsCount = 0;

                    foreach ($round as $shot)
                    {
                        $numericPoints = $shot->points == 'X' ? 10 : $shot->points;

                        $points += $numericPoints;
                        ++$pointsCount;

                        ++$specificPoints[$shot->points];

                        if ($shot->points == 'X')
                            ++$specificPoints[10];

                        ++$shotsCount;
                    }

                    ++$roundsCount;
                }
            }
        }

        $average = $points / $pointsCount;

        $specificPointsJsonReady = [];

        foreach ($specificPoints as $specificPointName => $specificPoint)
            $specificPointsJsonReady[] = [(string)$specificPointName, $specificPoint];

        // $scorecards = Scorecard::find(['competition' => $competition->id, 'player' => $player->id]);
        // $shots = 0;
        // $shotRoundsCount = [];
        // $shotRounds = [];
        // $roundShotCount = [];
        // $roundShot = [];

        // foreach ($scorecards as $scorecard)
        // {
        //     foreach ($scorecard->shots as $shot)
        //     {
        //         $shots++;

        //         if (!array_key_exists($shot->shot, $shotRounds))
        //         {
        //             $shotRoundsCount[$shot->shot] = 0;
        //             $shotRounds[$shot->shot] = 0;
        //         }

        //         $shotRoundsCount[$shot->shot]++;
        //         $shotRounds[$shot->shot] += $shot->points == 'X' ? 10 : $shot->points;

        //         if (!array_key_exists($shot->round, $roundShot))
        //         {
        //             $roundShotCount[$shot->round] = 0;
        //             $roundShot[$shot->round] = 0;
        //         }

        //         $roundShotCount[$shot->round]++;
        //         $roundShot[$shot->round] += $shot->points == 'X' ? 10 : $shot->points;
        //     }
        // }

        // foreach ($shotRoundsCount as $shot => $count)
        //     $shotRounds[$shot] /= $count;

        // foreach ($roundShotCount as $round => $count)
        //     $roundShot[$round] /= $count;

        // $shotRoundRows = [];

        // foreach ($shotRounds as $shot => $points)
        //     $shotRoundRows[] = [$shot, $points];

        // $roundShotRows = [];

        // foreach ($roundShot as $round => $points)
        //     $roundShotRows[] = [$round, $points];

        return view('competitions.inspect', compact('competition', 'player', 'scorecards', 'shots', 'shotRounds', 'roundShot', 'shotRoundRows', 'roundShotRows', 'points', 'pointsCount', 'average', 'specificPoints', 'specificPointsJsonReady'));
    }
}

resources/views/competitions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">@lang('competitions.create')</div>
                <div class="panel-body">
                    <form role="form" method="POST" action="{{ route('competitions.store') }}">
                        {!! csrf_field() !!}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name">@lang('competitions.name')</label>
                            <input type="text" class="form-control" name="name" id="name" value="{{ old('name') }}" placeholder="@lang('competitions.name')">

                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group{{ $errors->has('distance') ? ' has-error' : '' }}">
                            <label for="distance">@lang('competitions.distance')</label>
                            <input type="number" class="form-control" name="distance" id="distance" value="{{ old('distance') }}" placeholder="@lang('competitions.distance')">

                            @if ($errors->has('distance'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('distance') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group{{ $errors->has('shots_per_end') ? ' has-error' : '' }}">
                            <label for="shots-per-end">@lang('competitions.shots-per-end')</label>
                            <input type="number" class="form-control" name="shots_per_end" id="shots-per-end" value="{{ old('shots_per_end') }}" placeholder="@lang('competitions.shots-per-end')">

                            @if ($errors->has('shots_per_end'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('shots_per_end') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group{{ $errors->has('points_type') ? ' has-error' : '' }}">
                            <label>@lang('competitions.points-type')</label>
                            <div class="radio">
                                <label for="options-type-per-end">
                                    <input type="radio" name="points_type" id="options-type-per-end" value="per_end"@if (old('points_type') == 'per_end' or old('points_type') == null) checked @endif>
                                    @lang('competitions.points-type.per-end')
                                </label>
                            </div>
                            <div class="radio">
                                <label for="options-type-per-shot">
                                    <input type="radio" name="points_type" id="options-type-per-shot" value="per_shot"@if (old('points_type') == 'per_shot') checked @endif>
                                    @lang('competitions.points-type.per-shot')
                                </label>
                            </div>

                            @if ($errors->has('points_type'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('points_type') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">
                                @lang('competitions.create')
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/competitions/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">@lang('actions.edit'): {{ $competition->name }}</div>

                <div class="panel-body">
					<form action="/competitions/{{ $competition->id }}" method="POST">
						{{ csrf_field() }}
						{{ method_field('PATCH') }}

						<div class="form-group">
							<label for="name">@lang('competitions.name')</label>
							<input type="text" name="name" id="name" class="form-control" value="{{ $competition->name }}" placeholder="@lang('competitions.name')">
						</div>

						<div class="form-group">
							<button type="submit" class="btn btn-primary">@lang('actions.update')</button>
						</div>
					</form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/competitions/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    @lang('competitions.index')

                    @role(['owner', 'admin'])
                        <a href="{{ route('competitions.create') }}" class="pull-right">@lang('actions.create')</a>
                    @endrole
                </div>

                <div class="panel-body">
					<ul class="list-group">
						@foreach ($competitions as $competition)
							<li class="list-group-item">
                                <a href="{{ $competition->path() }}">{{ $competition->name }}</a>

                                @role(['owner', 'admin'])
                                    <a href="{{ $competition->path() }}/edit" class="pull-right">@lang('actions.edit')</a>
                                @endrole
                            </li>
						@endforeach
					</ul>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/competitions/inspect.blade.php
@extends('layouts.app')

@section('header')
    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

        // Load the Visualization API and the corechart package.
        google.charts.load('current', {'packages':['corechart']});

        // Set a callback to run when the Google Visualization API is loaded.
        google.charts.setOnLoadCallback(drawChart);

        // Callback that creates and populates a data table,
        // instantiates the pie chart, passes in the data and
        // draws it.
        function drawChart() {

            // Create the data table.
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Punten');
            data.addColumn('number', 'Aantal');
            data.addRows({!! json_encode($specificPointsJsonReady) !!});

            // Set chart options
            var options = {'title':'Geschoten',
                           'width':500,
                           'height':300};

            // Instantiate and draw our chart, passing in some options.
            var chart = new google.visualization.ColumnChart(document.getElementById('chart-averagepoints'));
            chart.draw(data, options);

            // // Create the data table.
            // var data = new google.visualization.DataTable();
            // data.addColumn('string', 'Ronde');
            // data.addColumn('number', 'Punten');
            // data.addRows([
            //     ["1", 24],
            //     ["2", 24],
            //     ["3", 24],
            // ]);

            // // Set chart options
            // var options = {'title':'Punten per ronde',
            //                'width':500,
            //                'height':300};

            // // Instantiate and draw our chart, passing in some options.
            // var chart = new google.visualization.ColumnChart(document.getElementById('chart-averageperend'));
            // chart.draw(data, options);
        }
    </script>
@stop

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">@lang('competitions.inspect'): {{ $player->name }}{{ $player->nhbid ? ' ['.$player->nhbid.']' : '' }} in {{ $competition->name }}</div>

                <div class="panel-body">
                    @lang('competitions.number-of-shots'): <strong>{{ $pointsCount }}</strong><br>
                    @lang('competitions.points'): <strong>{{ $points }}</strong><br>
                    @lang('competitions.average-points'): <strong>{{ number_format($average, 1, ',', '.') }}</strong>

                    <div id="chart-averagepoints" style="width:500;height:300"></div>
                    <div id="chart-averageperend" style="width:500;height:300"></div>

                    @foreach ($competition->games as $game)
                        <div class="panel panel-default">
                            <div class="panel-heading">{{ $game->date }}</div>

                            <div class="panel-body">
                                @foreach ($game->scorecards as $scorecard)
                                    <div class="panel panel-default">
                                        <div class="panel-heading"><strong>{{ $scorecard->place }}</strong>, @lang('competitions.track') <strong>{{ $scorecard->track }}</strong></div>

                                        <div class="panel-body">
                                            <table class="table table-bordered table-condensed">
                                                <tbody>
                                                    @foreach ($scorecard->rounds() as $round)
                                                        <tr>
                                                            {{-- <td>3</td> --}}
                                                            @foreach ($round as $shot)
                                                                <td>{{ $shot->points }}</td>
                                                            @endforeach
                                                            {{--
                                                            <td>30</td>
                                                            <td>30</td>
                                                            <td>3</td>
                                                            <td>3</td>
                                                            <td>3</td>
                                                            --}}
                                                        </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/competitions/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ $competition->name }}

                    @role(['owner', 'admin'])
                        <a href="/competitions/{{ $competition->id }}/edit" class="pull-right">@lang('actions.edit')</a>
                    @endrole
                </div>

                <div class="panel-body">
                    <div class="competition-distance">
                        <label>@lang('competitions.distance'): </label>
                        <div>{{ $competition->distance }}m</div>
                    </div>

                    <div class="competition-shots-per-end">
                        <label>@lang('competitions.shots-per-end'): </label>
                        <div>{{ $competition->shots_per_end }}</div>
                    </div>

                    <div class="competition-points-type">
                        <label>@lang('competitions.points-type'): </label>
                        <div>{{ ucfirst(str_replace('_', ' ', $competition->points_type)) }}</div>
                    </div>

                    <br>
                    <a href="{{ route('competitions.games.index', ['competition' => $competition]) }}">@lang('competitions.games')</a><br>
                    <br>

                    <div class="panel panel-default">
                        <div class="panel-heading">@lang('competitions.inspect')</div>
                        <div class="panel-body">
                            <ul class="list-group">
                                @foreach ($players as $player)
                                    <li class="list-group-item">
                                        <a href="{{ route('competitions.inspect', ['competition' => $competition, 'player' => $player]) }}">{{ $player->name }}</a>
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop