app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('competitions');
});

Route::group(['middleware' => 'web'], function(){
	Route::match(['get', 'post'], 'update', 'UpdateController@index');

	Route::auth();

	// Route::get('/home', 'HomeController@index');

	Route::singularResourceParameters();

	Route::resource('clubs', 'ClubsController');
	Route::resource('competitions', 'CompetitionsController');
	Route::resource('competitions.games', 'GamesController');
	Route::resource('competitions.games.scorecards', 'ScorecardsController');
	Route::resource('players', 'PlayersController');
	Route::resource('ranks', 'RanksController');
	Route::resource('users', 'UsersController');

	Route::post('competitions/{competition}/find', 'CompetitionsController@find');
	Route::get('competitions/{competition}/inspect/{player}', 'CompetitionsController@inspect')->name('competitions.inspect');
});

app/Competition.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Competition extends Model
{
    protected $fillable = [
        'name',
        'shots_per_end',
        'distance',
        'points_type',
    ];

    public function games()
    {
    	return $this->hasMany(Game::class);
    }

    public function scorecards()
    {
        return $this->hasManyThrough(Scorecard::class, Game::class);
    }

    public function addGame(Game $game)
    {
    	return $this->games()->save($game);
    }

    public function path()
    {
    	return '/competitions/'.$this->id;
    }
}

app/Game.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    public $fillable = ['date'];

    public function competition()
    {
    	return $this->belongsTo(Competition::class);
    }

    public function scorecards()
    {
    	return $this->hasMany(Scorecard::class);
    }

    public function addScorecard(Scorecard $scorecard)
    {
        return $this->scorecards()->save($scorecard);
    }

    public function path()
    {
    	return route('competitions.games.show', [
    		'competition' => $this->competition->id,
    		'game' => $this->id,
    	]);
    }
}

app/Http/Controllers/CompetitionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Player;
use App\Scorecard;
use App\Competition;
use Khill\Lavacharts\Lavacharts;

class CompetitionsController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:owner|admin', ['except' => [
            'index',
            'show',
            'inspect',
        ]]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $competitions = Competition::orderBy('created_at', 'desc')->get();

        return view('competitions.index', compact('competitions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('competitions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:competitions',
            'distance' => 'required',
            'points_type' => 'required',
        ]);

        $competition = Competition::create($request->all());

        return redirect($competition->path());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Competition $competition)
    {
        $players = [];

        foreach ($competition->games as $game)
        {
            foreach ($game->scorecards as $scorecard)
            {
                if (!array_key_exists($scorecard->player->id, $players))
                    $players[$scorecard->player->id] = $scorecard->player;
            }
        }

        return view('competitions.show', compact('competition', 'players'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Competition $competition)
    {
        return view('competitions.edit', compact('competition'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Competition $competition)
    {
        $competition->update($request->all());

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function find(Request $request, Competition $competition)
    {
        $player = Player::find($request->player_id);

        return redirect('/competitions-inspect/'.$competition->id.'/'.$player->id);
    }

    public function inspect(Competition $competition, Player $player)
    {
        $points = 0;
        $pointsCount = 0;

        $specificPoints = [0 => 0, 1 => 0, 2 => 0, 3 => 0, 4 => 0, 5 => 0, 6 => 0, 7 => 0, 8 => 0, 9 => 0, 10 => 0, 'X' => 0];

        foreach ($competition->games as $game)
        {
            foreach ($game->scorecards as $scorecard)
            {
                $roundsCount = 0;

                foreach ($scorecard->rounds() as $round)
                {
                    $shotsCount = 0;

                    foreach ($round as $shot)
                    {
                        $numericPoints = $shot->points == 'X' ? 10 : $shot->points;

                        $points += $numericPoints;
                        ++$pointsCount;

                        ++$specificPoints[$shot->points];

                        if ($shot->points == 'X')
                            ++$specificPoints[10];

                        ++$shotsCount;
                    }

                    ++$roundsCount;
                }
            }
        }

        $average = $points / $pointsCount;

        $specificPointsJsonReady = [];

        foreach ($specificPoints as $specificPointName => $specificPoint)
            $specificPointsJsonReady[] = [(string)$specificPointName, $specificPoint];

        // $scorecards = Scorecard::find(['competition' => $competition->id, 'player' => $player->id]);
        // $shots = 0;
        // $shotRoundsCount = [];
        // $shotRounds = [];
        // $roundShotCount = [];
        // $roundShot = [];

        // foreach ($scorecards as $scorecard)
        // {
        //     foreach ($scorecard->shots as $shot)
        //     {
        //         $shots++;

        //         if (!array_key_exists($shot->shot, $shotRounds))
        //         {
        //             $shotRoundsCount[$shot->shot] = 0;
        //             $shotRounds[$shot->shot] = 0;
        //         }

        //         $shotRoundsCount[$shot->shot]++;
        //         $shotRounds[$shot->shot] += $shot->points == 'X' ? 10 : $shot->points;

        //         if (!array_key_exists($shot->round, $roundShot))
        //         {
        //             $roundShotCount[$shot->round] = 0;
        //             $roundShot[$shot->round] = 0;
        //         }

        //         $roundShotCount[$shot->round]++;
        //         $roundShot[$shot->round] += $shot->points == 'X' ? 10 : $shot->points;
        //     }
        // }

        // foreach ($shotRoundsCount as $shot => $count)
        //     $shotRounds[$shot] /= $count;

        // foreach ($roundShotCount as $round => $count)
        //     $roundShot[$round] /= $count;

        // $shotRoundRows = [];

        // foreach ($shotRounds as $shot => $points)
        //     $shotRoundRows[] = [$shot, $points];

        // $roundShotRows = [];

        // foreach ($roundShot as $round => $points)
        //     $roundShotRows[] = [$round, $points];

        return view('competitions.inspect', compact('competition', 'player', 'scorecards', 'shots', 'shotRounds', 'roundShot', 'shotRoundRows', 'roundShotRows', 'points', 'pointsCount', 'average', 'specificPoints', 'specificPointsJsonReady'));
    }
}

app/Http/Controllers/GamesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Game;
use App\Competition;

class GamesController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:owner|admin', ['except' => [
            'index',
            'show',
        ]]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Competition $competition)
    {
        $games = Game::all();

        return view('competitions.games.index', compact('competition', 'games'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Competition $competition)
    {
        return view('competitions.games.create', compact('competition'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Competition $competition)
    {
        $game = $competition->addGame(new Game($request->all()));

        return redirect(route('competitions.games.show', ['competition' => $competition, 'game' => $game]));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Competition $competition, Game $game)
    {
        return view('competitions.games.show', ['competition' => $competition, 'game' => $game]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/competitions/games/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">@lang('competitions/games.create')</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('competitions.games.store', ['competition' => $competition]) }}">
                        {!! csrf_field() !!}

                        <div class="form-group{{ $errors->has('date') ? ' has-error' : '' }}">
                            <label class="col-md-4 control-label">@lang('competitions/games.date')</label>

                            <div class="col-md-6">
                                <input type="date" class="form-control" name="date" value="{{ old('date') }}" placeholder="@lang('competitions/games.date')">

                                @if ($errors->has('date'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('date') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    @lang('actions.store')
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/competitions/games/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    @lang('competitions/games.index')

                    @role(['owner', 'admin'])
                        <a href="{{ route('competitions.games.create', ['competition' => $competition->id]) }}" class="pull-right">@lang('actions.create')</a>
                    @endrole
                </div>

                <div class="panel-body">
					<ul class="list-group">
						@foreach ($games as $game)
							<li class="list-group-item">
                                <a href="{{ $game->path() }}">{{ $game->date }}</a>

                                @role(['owner', 'admin'])
                                    <a href="{{ $game->path() }}/edit" class="pull-right">@lang('actions.edit')</a>
                                @endrole
                            </li>
						@endforeach
					</ul>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/competitions/games/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ $game->date }}
                </div>

                <div class="panel-body">
                    <div class="game-competition">
                        <label>@lang('competitions/games.competition'): </label>
                        <div><a href="{{ $game->competition->path() }}">{{ $game->competition->name }}</a></div>
                    </div>

                    <br>
                    <a href="{{ route('competitions.games.scorecards.index', ['competition' => $competition, 'game' => $game]) }}">@lang('competitions/games.scorecards')</a>
                </div>
            </div>
        </div>
    </div>
</div>
@stop