app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('competitions');
});

Route::group(['middleware' => 'web'], function(){
	Route::match(['get', 'post'], 'update', 'UpdateController@index');

	Route::auth();

	// Route::get('/home', 'HomeController@index');

	Route::singularResourceParameters();

	Route::resource('clubs', 'ClubsController');
	Route::resource('competitions', 'CompetitionsController');
	Route::resource('competitions.games', 'GamesController');
	Route::resource('competitions.games.scorecards', 'ScorecardsController');
	Route::resource('players', 'PlayersController');
	Route::resource('ranks', 'RanksController');
	Route::resource('users', 'UsersController');

	Route::post('competitions/{competition}/find', 'CompetitionsController@find');
	Route::get('competitions/{competition}/inspect/{player}', 'CompetitionsController@inspect')->name('competitions.inspect');
});

app/Club.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Club extends Model
{
	public $fillable = ['name', 'place', 'nhbid'];

	public function players()
	{
		return $this->hasMany(Player::class);
	}

	public function addPlayer(Player $player)
	{
		return $this->players()->save($player);
	}

    public function path()
    {
    	return route('clubs.show', ['club' => $this]);
    }

    public function editPath()
    {
    	return route('clubs.edit', ['club' => $this]);
    }
}

app/Http/Controllers/ClubsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Club;

class ClubsController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:owner|admin|club-manager', ['except' => [
            'index',
            'show',
        ]]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clubs = Club::orderBy('name')->orderBy('place')->get();

        return view('clubs.index', compact('clubs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clubs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'    => 'required|unique:clubs',
            'place'    => 'required',
            'nhbid'    => 'unique:clubs',
        ]);

        Club::create($request->all());

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Club $club)
    {
        return view('clubs.show', compact('club'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Club $club)
    {
        return view('clubs.edit', compact('club'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Club $club)
    {
        $this->validate($request, [
            'name' => 'required|unique:clubs,name,'.$club->id,
            'place' => 'required',
            'nhbid' => 'unique:clubs,nhbid,'.$club->id,
        ]);

        $club->update($request->all());

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/clubs/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">@lang('clubs.create')</div>
                <div class="panel-body">
                    <form role="form" method="POST" action="{{ route('clubs.store') }}">
                        {!! csrf_field() !!}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label class="control-label">@lang('clubs.name')</label>

                            <input type="text" class="form-control" name="name" value="{{ old('name') }}" placeholder="@lang('clubs.name')" required>

                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group{{ $errors->has('place') ? ' has-error' : '' }}">
                            <label class="control-label">@lang('clubs.place')</label>

                            <input type="text" class="form-control" name="place" value="{{ old('place') }}" placeholder="@lang('clubs.place')" required>

                            @if ($errors->has('place'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('place') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group{{ $errors->has('nhbid') ? ' has-error' : '' }}">
                            <label class="control-label">@lang('clubs.nhbid')</label>

                            <input type="text" class="form-control" name="nhbid" value="{{ old('nhbid') }}" placeholder="@lang('clubs.nhbid')">

                            @if ($errors->has('nhbid'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('nhbid') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">
                                @lang('actions.store')
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/clubs/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">@lang('actions.edit'): {{ $club->name }}</div>
                <div class="panel-body">
                    <form role="form" method="POST" action="{{ route('clubs.store') }}">
                        {!! csrf_field() !!}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label class="control-label">@lang('clubs.name')</label>

                            <input type="text" class="form-control" name="name" value="{{ ($name = old('name')) ? $name : $club->name }}" placeholder="@lang('clubs.name')" required>

                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group{{ $errors->has('place') ? ' has-error' : '' }}">
                            <label class="control-label">@lang('clubs.place')</label>

                            <input type="text" class="form-control" name="place" value="{{ ($place = old('place')) ? $place : $club->place }}" placeholder="@lang('clubs.place')" required>

                            @if ($errors->has('place'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('place') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group{{ $errors->has('nhbid') ? ' has-error' : '' }}">
                            <label class="control-label">@lang('clubs.nhbid')</label>

                            <input type="text" class="form-control" name="nhbid" value="{{ ($nhbid = old('nhbid')) ? $nhbid : $club->nhbid }}" placeholder="@lang('clubs.nhbid')">

                            @if ($errors->has('nhbid'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('nhbid') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">
                                @lang('actions.update')
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/clubs/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    @lang('clubs.index')

                    @role(['owner', 'admin'])
                        <a href="{{ route('clubs.create') }}" class="pull-right">@lang('actions.create')</a>
                    @endrole
                </div>

                <div class="panel-body">
					<ul class="list-group">
						@foreach ($clubs as $club)
							<li class="list-group-item">
                                <a href="{{ $club->path() }}">{{ $club->name }} ({{ $club->place }})@if ($club->nhbid)  [{{ $club->nhbid }}] @endif</a>

                                @role(['owner', 'admin'])
                                    <a href="{{ $club->path() }}/edit" class="pull-right">@lang('actions.edit')</a>
                                    {{-- <a href="#" class="pull-right">@lang('actions.delete')</a> --}}
                                @endrole
                            </li>
						@endforeach
					</ul>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/clubs/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ $club->name }}

                    @role(['owner', 'admin'])
                        <a href="{{ $club->editPath() }}" class="pull-right">@lang('actions.edit')</a>
                    @endrole
                </div>
                <div class="panel-body">
                    <div class="club-place">
                        <label>@lang('clubs.place'): </label>
                        <div>{{ $club->place }}</div>
                    </div>

                    <div class="club-nhbid">
                        <label>@lang('clubs.nhbid'): </label>
                        <div>{{ $club->nhbid }}</div>
                    </div>

                    <div class="panel panel-default">
                        <div class="panel-heading">@lang('app.players')</div>
                        <div class="panel-body">
                            <ul class="list-group">
                                @foreach ($club->players as $player)
                                    <li class="list-group-item">
                                        <a href="{{ $player->path() }}">{{ $player->name }}{{ $player->rank ? ' ('.$player->rank->name.')' : '' }}{{ $player->nhbid ? ' ['.$player->nhbid.']' : '' }}</a>

                                        @role(['owner', 'admin'])
                                            <a href="{{ $player->editPath() }}" class="pull-right">@lang('actions.edit')</a>
                                        @endrole
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection